on:
  workflow_dispatch:
    inputs:
      version:
        description: version of gitit deb package
        type: string
        required: true

env:
  IMAGE_NAME: gitit

jobs:
  build:
    name: Build and publish container image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Install Podman
        uses: gacts/install-podman@v1.1.0
        
      - name: Build
        run: podman build -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          podman tag $IMAGE_NAME $IMAGE_ID:$VERSION
          podman push $IMAGE_ID:$VERSION
          
          VERSION="${{ inputs.version }}"
          echo VERSION=$VERSION
          podman tag $IMAGE_NAME $IMAGE_ID:$VERSION
          podman push $IMAGE_ID:$VERSION
